### ISSUE TITLE
When does this oss test Laravel 9?

### ISSUE THREAD

**Issue by pomcho555** [shiftonelabs/laravel-sqs-fifo-queue#14]
Thank you for your great project. Laravel9 was released February 8th, 2022. So, we plan to use Laravel 9 as a web application in our project. And I have a question. Does this oss have plans to test Larave9? I want to know a rough roadmap on it for me and other developers waiting for that.

Also, I will share the information on our local testing result with Laravel9 if I get it.

**Comment by Binternet** [comment]
I'm not sure what `oss test` is and maybe you mean something else.
But I've successfully installed this on Laravel 9.30.1 and it works, just add the package and the credentials on `config/queues.php` and that's all.

**Comment by pomcho555** [comment]
Thank you for your kind report. 
I have to share my experiment with you. This oss should do the trick on Laravel 9.2 like you did.
We also tried some tests to verify if it works well with sample messages on SQS, and they were successful.

My gentle suggestion is that the README.md should have this information for Laravel 9.x users.

**Comment by Binternet** [comment]
Added this commit:
https://github.com/Binternet/laravel-sqs-fifo-queue/commit/7986e6509e11c57270238073729e2b8fb95cab0e

If this looks OK let me know and i'll open a PR.

**Comment by patrickcarlohickman** [comment]
@pomcho555 , @Binternet ,

I appreciate the patience on this. The package has been updated to support both Laravel 9x and 10x, as well as PHP 8+. The new 3.0.0 tag for this support was released today.

Thanks,
Patrick
