### ISSUE TITLE
FATAL ERROR - Symfony\Component\ErrorHandler\Error\FatalError

### ISSUE THREAD

**Issue by encodiaweb** [shiftonelabs/laravel-sqs-fifo-queue#16]
Laravel version: 9.44.0
PHP version: 8.1

`Declaration of ShiftOneLabs\LaravelSqsFifoQueue\Support\Str::substr($string, $start, $length = null) must be compatible with Illuminate\Support\Str::substr($string, $start, $length = null, $encoding = 'UTF-8')`

It looks like this is a major issue, because it breaks queue workers.
  
I think extending `Illuminate\Support\Str` is no more necessary.

Thank you

**Comment by danganf** [comment]
Soluction:
`src/Support/Str.php:47`

`    public static function substr($string, $start, $length = null, $encoding = 'UTF-8')
    {
        return mb_substr($string, $start, $length, 'UTF-8');
    }`

**Comment by danganf** [comment]
Pull Request create
https://github.com/shiftonelabs/laravel-sqs-fifo-queue/pull/17

**Comment by kaamoss** [comment]
Two months later here, can we please get this merged in so that we don't all have to fork this repo to use it with laravel 9?

**Comment by patrickcarlohickman** [comment]
@encodiaweb , @kaamoss ,

I appreciate the patience on this. The package has been updated to support both Laravel 9x and 10x, as well as PHP 8+. The new 3.0.0 tag for this support was released today.

Please let me know if you run into any more issues.

Thanks,
Patrick
