### ISSUE TITLE
Target class [XXX] does not exist of message from AWS SQS Queue

### ISSUE THREAD

**Issue by xpalacinengelsolar** [shiftonelabs/laravel-sqs-fifo-queue#26]
When Laravel process queue, not resolve class from SQS message.

The SQS message is:
`JSON
{
   "uuid":"1234",
   "displayName":"offer_status_changed",
   "job":"offer_status_changed",
   ...
   "data":{
      "id":71,
      ...
   }
}
`

The job name not include class namespace and Laravel throw errors:
- `Target class [offer_status_changed] does not exist`
- `[object] (ReflectionException(code: -1): Class \"offer_status_changed\" does not exist`

I understand that job should include namespace with method `"job":"App\\Jobs\\offer_status_changed@handle",`

**Comment by MattWiseParking** [comment]
your sending a job class called offer_status_changed to the queue and the class can not be resolved

**Comment by patrickcarlohickman** [comment]
@xpalacinengelsolar ,

It doesn't seem like you dispatched your job correctly. It looks like you dispatched the string "offer_status_changed", instead of dispatching the job itself.

This issue is not related to this package, and is handled by the queuing functionality built into Laravel. You'll need to use Laravel's support options for help.

Thanks,
Patrick

**Comment by xpalacinengelsolar** [comment]
I create the class in `app\Jobs\offer_status_changed.php` with `class offer_status_changed implements ShouldQueue,` and enable queue with `php artisan queue:work`

**Comment by MattWiseParking** [comment]
> I create the class in `app\Jobs\offer_status_changed.php` with `class offer_status_changed implements ShouldQueue,` and enable queue with `php artisan queue:work`

The naming convention of the class/file name needs to be changed to OfferStatusChanged.  ensure name space is correct.

**Comment by patrickcarlohickman** [comment]
> I create the class in `app\Jobs\offer_status_changed.php` with `class offer_status_changed implements ShouldQueue,` and enable queue with `php artisan queue:work`

@xpalacinengelsolar How did you dispatch your job?
