### ISSUE TITLE
Please provide support for Laravel 7.x.

### ISSUE THREAD

**Issue by kotenarok** [shiftonelabs/laravel-sqs-fifo-queue#8]
Please provide support for Laravel 7.x.

**Comment by patrickcarlohickman** [comment]
@kotenarok I haven't tested it on 7.x, but the composer file won't prevent you from installing on 7.x. Have you tried it and run into an issue?

Thanks,
Patrick

**Comment by patrickcarlohickman** [comment]
@kotenarok 

So, I tested it on Laravel 7x, and it did work, but I had to specifically downgrade the installed version of ramsey/uuid to get it to install.

I have tagged a new release (1.1.3) that updates the ramsey/uuid dependency so you won't need to do this anymore. The package should install and work in Laravel 7x without any issues.

Thanks,
Patrick
